### ISSUE TITLE
Review fields for optionality

### ISSUE THREAD

**Issue by fugu13** [adlnet/xapi-profiles#1]
Right now most fields are not marked as optional, and a few that aren't probably should be. An important consideration while reviewing for this is, in many cases it will not be possible to understand how to use the profiles without extensive metadata -- verbs need definitions, and patterns of statements need descriptions of what they mean, and so forth. That suggests most of the descriptive metadata should stay required.

**Comment by garemoko** [comment]
+1 It would be good to add a 'required' column to all the tables like we have in xapi.

**Comment by fugu13** [comment]
Thinking about it, I intend to as part of this add language that says:

All elements not marked as optional are required in all cases if the enclosing object is present, and if objects or strings, must be non-empty. Elements marked as optional may have additional requirements stated elsewhere, including ones that make them required in certain circumstances.
