### ISSUE TITLE
Make sure it is possible to express alternatives in statement rules

### ISSUE THREAD

**Issue by fugu13** [adlnet/xapi-profiles#109]
Aimed at situations like: an actor must be identified by an account or an mbox_sha1sum.

**Comment by garemoko** [comment]
If this is possible, presumably by using some JSONPath magic, we should include it as an example (but not the only example, due to its complexity).

**Comment by fugu13** [comment]
I think this will require we allow an operator to join multiple JSONPath queries. This is outside of the original JSONPath specification, but several libraries have adopted the pipe, |, as this operator.
