### ISSUE TITLE
Profile Ontology and @Context 

### ISSUE THREAD

**Issue by jhaag75** [adlnet/xapi-profiles#112]
@fugu13 
ADL is working on taking the old profiles published according to the vocab spec, and creating JSON-LD docs based on the profile spec. As part of that exercise, it would be good to have the @context JSON-LD and any ontologies that will be used. Otherwise, the profile data expressed as JSON-LD won't validate. I noticed you created a sample @context for the SCORM profile. 

Can you also please publish a baseline @context doc to be used with most profiles and the new profile ontology?

**Comment by fugu13** [comment]
Yep, context is in

**Comment by jhaag75** [comment]
Thank you! FYI: 
xapi namespace should be "xapi": "https://w3id.org/xapi/ontology#",

 instead of 

"xapi": "http://purl.org/xapi/ontology#",

**Comment by jhaag75** [comment]
@fugu13 

also can you update "profile": "http://purl.org/xapi/profile/ontology#",

to

"profile:" "https://w3id.org/xapi/profile/ontology#",

BTW, do you have a draft of the profile ontology yet?

**Comment by fugu13** [comment]
Oh yeah, I keep pulling from old places and forgetting to update.

No profile ontology yet, but you won't see any surprises.

**Comment by jhaag75** [comment]
10-4 thanks bud! You expect to have that this week? Just trying to get an idea for planning purposes...

**Comment by jhaag75** [comment]
Also I noticed in the context that type is aliased but @id isn't
