### ISSUE TITLE
TOC / Accessibility / Readability

### ISSUE THREAD

**Issue by jhaag75** [adlnet/xapi-profiles#113]
Would like to at least see a table of contents provided for this spec when it is near a 1.0 state. Synchronization with gitbook would be nice for improved navigation, readability, and accessibility.

**Comment by garemoko** [comment]
+1 to a table of contents. 

-1 to Gitbook as I seem to remember it adding complexity around editing the document (though my recollection is hazy - I remember not liking up but I don't really recall why). Definitely nothing against having a Gitbook fork of the finished version though.
