### ISSUE TITLE
TinCan and Activity Streams IRIs?

### ISSUE THREAD

**Issue by jhaag75** [adlnet/xapi-profiles#114]
While adopting the new profile spec is going to be exciting we haven't discussed what to do about existing concepts (verbs, activity types, attachment types) out in the wild that existed before the work around vocabulary or the profile spec. 

What are we to do with the tincan and activity streams IRIs? If they aren't inScheme of a specific profile then how will they be discovered or searched from the profile server? The Activity Streams IRIs are already broken/unresolvable. Should they be deprecated? Should they be associated with new IRIs when the new profile server is stood up? What are we to do with verb IRIs that aren't inScheme / associated with profiles? 

DISC posted a related blog post about this last August where I commented. 
http://datainteroperability.org/2016/08/how-important-are-consistent-identifiers-for-vocabulary/

The profile spec addresses how to handle new profiles, concepts, and statement templates. But should we take any action on the old stuff?

In addition to the IRIs, what about the old profiles that were published here: https://registry.tincanapi.com/#home/profiles 

ADL would like to hear your thoughts on how to best preserve or update previous profile and statement template work so that it isn't lost.

**Comment by fugu13** [comment]
As we discussed during one of the profile meetings, my recommendation for verbs like this is publish a profile version with the activity streams verbs deprecated and replacements, and immediately publish a second version only containing the replacements without the activity streams verbs, using all the mechanics provided for in the spec for connecting replacements to deprecated terms.

It'd probably be reasonable to fold this into an ADL managed profile, though I suppose I have a bit of a claim since I'm the one who suggested using those verbs in the first place (back when they had nice, resolvable IRIs that led to clean descriptions... sometimes the web is so impermanent).

**Comment by jhaag75** [comment]
Can you point me to the mechanics in the spec? I think an example would be helpful (here or in the spec) too.

We will try to update all existing profiles as you suggest. I hear ya on impermanence, but it's just the way it is. I just want to try and improve things and try to promote good practices moving forward, regardless of the past. 

What you proposed seems like we can only do this for those tincan and activity streams concepts that are used in current profiles. However, there are many concepts listed in the tincan registry that don't belong to any one specific profile or may have not be used by anyone yet implementing xAPI. 

And if we create an additional ADL "profile" with all of those orphan concepts then that's not really a profile. It's just a list of concepts IMO (vocabulary). A profile is documentation intended to provide protocol or application semantics or application-specific extensions. If some concepts are inScheme of specific profiles, but all others that are orphans are not it makes me wonder if ALL concepts should just be in a single base ADL profile (as you suggested for the orphans). In other words all concepts are centrally managed and new ones can be submitted, etc but they belong to a base profile/vocabulary. This seems to be the approach of activity streams, Caliper, and others as well. I think it would make since to do something like this and to only have extensions and statement templates in profiles. It seems like that would be much easier in terms of maintenance and would possible solve some of our challenges in preserving legacy concepts from tincan and activity streams too...

**Comment by fugu13** [comment]
You'll find the important pieces all in the table of https://github.com/DataInteroperability/xapi-profiles/blob/master/xapi-profiles-spec.md#core-concepts-verbs-activity-types-and-attachment-usage-types , particularly in related and relatedMatch.

**Comment by fugu13** [comment]
I'd recommend they be incorporated in a particular profile. Broadly, I'd recommend coining of concepts be done through profiles to provide management and incorporation into profile servers. Some profiles may even, very rarely, be just a single verb.

I wouldn't say put all concepts into a single ADL base profile; in particular, best to allow communities interested in active management of things related to concepts to do so. Sweeping up a bit of verb clutter that no one has particular ownership of into some ADL profile makes some sense, though, especially as there's already a bit of eclecticism there.
