### ISSUE TITLE
Statement Template uniqueness

### ISSUE THREAD

**Issue by cr8onski** [adlnet/xapi-profiles#118]
>A profile SHOULD ensure each statement following any of its Statement Templates will match at most one Statement Template.

Is there a reason this is not a MUST?  It seems pattern testing is useless if this is not followed.

**Comment by garemoko** [comment]
I'm struggling to think of a good reason for an exception to this rule. Let's say you did legitimately have two non-exclusive templates that were used in patterns. If a statement matched one template, it wouldn't be available to match the other template due to the greedy nature of pattern matching.

**Comment by fugu13** [comment]
Honestly I'm thinking of removing the SHOULD completely -- the requirements-for-everything template is just such a nice pattern.

More broadly, it definitely *cannot* be a MUST; that would make it impossible to support use-cases like statements about a submodule that are within a parent module, matching both the parent module's general "additional statements about content" pattern and the submodule's specific statements about completion and such at the same time.
