### ISSUE TITLE
Pattern @id vs prefLabel and definition

### ISSUE THREAD

**Issue by cr8onski** [adlnet/xapi-profiles#120]
>A pattern with an @id MUST NOT include prefLabel, definition, or deprecated. A pattern without an @id MUST include prefLabel and definition. This is a top-level pattern.

Is this a JSON-LD thing, where if the @id is there the JSON-LD will be able to get those fields so don’t waste time including them and vice versa, or is there more to it than that?  And how does that third sentence fit into this?

**Comment by fugu13** [comment]
This is old language, but it wasn't JSON-LD, just two types of pattern with different usages. It has been replaced by an explicit boolean (`primary`) now. Some patterns are there just to be used by other patterns. Some patterns are legal definitions of sequences of statements. We don't need to provide textual glosses for ones that aren't the latter. 

Looks like during the merging prefLabel and definition missed the optional pass, though! Adding an issue.
