### ISSUE TITLE
Text/Clarity Changes in Using Profiles Section

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xapi-profiles#122]
Under "Using Profiles in Statements" , there are a few changes that I think would make things more clear:

1)  "Learning Record Providers creating statements that conform to matching profile-described statement templates and patterns"  - I think we can lose the word “matching”, this seems to be confusing.  I think we can agree that a Learning Record provider who is creating statements that conform to templates and patterns know they are building to that profile.

2)  " and statements containing a profile version as a category context activity MUST conform to any matching templates and patterns that profile version describes. " - Let's separate this requirement out from the previous point.  All requirements should (or MUST :) ) stand on their own.

3)  Hyphenate up-to-date.

**Comment by fugu13** [comment]
1. matching is a term used extensively in the profile spec to refer to very specific situations, it makes sense to continue using it here.

2. spot checking a variety of RFCs and other specifications, multiple MUST requirements are frequently placed in the same sentence. What's the source of this idea that requirements need to be separated apart when they're closely related?

3. Sure; is there some particular dictionary/style-guide we're using? No hyphens is a widely used spelling (albeit more often in England).

**Comment by garemoko** [comment]
On 2, we had a few occasions in xAPI where ambiguous requirements were as a result of lumping too much in together as a single requirement. It's almost always clearer to have shorter sentences and separate things out. Bulleted lists with indents or headings provide a way to group related requirements.

**Comment by andyjohnson** [comment]
I'm okay on 1 as my understanding of the spec has grown since I wrote this.  For 2, I always like requirements more granular as there is less room for error in interpretation and as long as we don't lose meaning, I don't see the harm.  For 3, just the way I'm used to seeing it.  I'm not that bullish on it if the non-hyphenated form is considered correct also.
