### ISSUE TITLE
Clarity Changes in Concepts Section

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xapi-profiles#123]
The Concepts section needs to have a bit more clarity and consistency when defining usage types.  First, I think we need to lose the idea of "Core Concepts" and focus on different Concept types.  I think combining the "like" types into one table as is done in the Core Concepts section is fine, but we should also have some text up front that describes that the tables below have the usage patterns dictated by the value of "type".  

I also think that the sections should re-iterate the types by avoiding words like "these" and say "Concepts with the type of Activity", for example.

As is an already known global change, requirements should be separated from guiding text.  This section does this in some places but not others.  We also may want to say that unless specified as "Optional", all table names/values are MUSTs for the specified type.

**Comment by fugu13** [comment]
I like core concepts as a way to organize things, but I'm not overly attached to it.

> We also may want to say that unless specified as "Optional", all table names/values are MUSTs for the specified type.

This is already fully handled by the document interpretation section: https://github.com/DataInteroperability/xapi-profiles/blob/master/xapi-profiles-spec.md#document-interpretation-and-general-restrictions

**Comment by garemoko** [comment]
I also came to the conclusion of ditching "core concepts". See suggested new wording here: https://github.com/DataInteroperability/xapi-profiles/issues/149
