### ISSUE TITLE
Text/Clarity Changes in Statement Templates

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xapi-profiles#125]
A few structural and text additions that could be beneficial:

1)  "A Statement Template describes one way statements following the profile may be structured.  "  This seems very loose.  What are the other ways?  I'd recommend just saying what they are and not getting into what doesn't exist.

2)  "Additionally, we recommend picking one of the determining properties to use in all Statement Templates in a profile, with different values in each, since this ensures each statement matches at most one Statement Template in a given profile."  - a couple things, we need to lose the personal pronouns :) - global.  We also need to describe who this is talking about.  Recommend:  “Additionally, profile authors SHOULD (or if you want to avoid the SHOULD, “it is recommended that profile authors”…) choose one of the determining properties to use in all Statement Templates within that profile, …”

3)  "A Statement Template Rule MUST include one or more of rule, any, all, or none. " - suggest code blocks for anything requiring a specific value.

4)  "The syntax of JSONPath is described at http://goessner.net/articles/JsonPath/index.html#e2,"  - I suggest should get this language in GitHub or to a more permanent source

**Comment by fugu13** [comment]
1. "One way" refers to a single statement template, the other ways are the other statement templates. We can reword to reduce confusion.

2. definitely, will reword into profile author requirement

3. yeah, there're a lot of those that aren't fully covered, that's one of the definite passes to do

4. weird as it is, that is the canonical page that everyone links to. Incorporating would be... a pretty big project, which I'm a bit loathe to do as there is an accepted definitive (albeit a bit loose in language) resource. Worth talking about more.

**Comment by andyjohnson** [comment]
I'm fine with 4, albeit weird :)  I really don't like incorporating, either.
