### ISSUE TITLE
"Rule" name change

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xapi-profiles#126]
Within Statement Template Rules, the "rule" element has to have values of "included", "excluded", or "recommended".  In SCORM this was multiplicity, which I think is a closer match to what the intention of this element does.  Open to other suggestions, but "rule" is very confusing, especially since it shows up in an array of "rules".

**Comment by fugu13** [comment]
A rename seems good. I'm not sure how the word multiplicity was used in SCORM but the concept here has nothing to do with the definition of the word multiplicity, so I would definitely not like to use that.

How about "presence"?

**Comment by garemoko** [comment]
How about "include"?

**Comment by fugu13** [comment]
Hmmm, "include": "excluded" gets contradictory then; in programming the general recommendation is to not use names that have values that contradict the meaning of the names

**Comment by garemoko** [comment]
Going back to the theme of "rule" how about "restriction"? Doesn't work so well with recommended, but then neither does rule.

**Comment by fugu13** [comment]
I'm going to tentatively go with `presence` since that seems to work well with all of included, excluded and recommended. If someone has a strong feeling otherwise, go ahead and reopen the issue with suggestions.
