### ISSUE TITLE
Out of Place Requirement

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xapi-profiles#127]
The following requirement is currently located in Statement Templates:

"If a statement matches a Statement Template's determining values and uses the profile version as a category context activity, it MUST be sent as part of a Pattern or Implied Pattern. " 

If reading normally, I'm not going to know what a Pattern or Implied Pattern is yet.  I suggest moving that requirement to that section or at the very least to right before that section so the transition is smoother.

**Comment by fugu13** [comment]
I'll look into what rearrangement most improves the flow

**Comment by garemoko** [comment]
I identified the same issue on my read-through today. My suggested solution was to add links to the terms so that people could click them to read more. https://github.com/DataInteroperability/xapi-profiles/issues/164

**Comment by fugu13** [comment]
Other requirements added elsewhere mean this text actually got removed completely as redundant
