### ISSUE TITLE
Remove All Incomplete Sections

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xapi-profiles#128]
A clean-up task, but an important one.  Sections of text like:  in Alignments and Statement References such as: 

"I'm unsure enough how to do this I propose we do not include statement reference constraints in the initial draft. It would probably be included as a special case in the statement template rules, above."

Should be scrubbed out.  If we want to open them as issues so people know this group thought about them, that would be more appropriate.

**Comment by fugu13** [comment]
Yes, those will all be scrubbed before 1.0.

**Comment by garemoko** [comment]
I've created individual issues for some of these. i'll leave them open rather than closing as duplicates because it might be useful to have a checklist.

**Comment by fugu13** [comment]
I believe this is done in the incoming PR
