### ISSUE TITLE
Patterns Are Two Things

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xapi-profiles#129]
Patterns in the spec are defined as "groups of statements matching particular statement templates".  We then go on to have a type with a value of "Pattern" that then has requirements which spell out the RULES that a pattern must follow.  The pattern is now both the set of statements AND the rules.  It ends up being confusing.  Suggest that there will be cases that certain behaviors are expected in a COP, often concerning Statements and their usage.  Patterns can govern acceptable usage....something like that.

**Comment by fugu13** [comment]
Yup, we can remove that ambiguity.
