### ISSUE TITLE
Short IDs for document resources

### ISSUE THREAD

**Issue by fugu13** [adlnet/xapi-profiles#13]
Using @id will require it to be a URI. In many ways this is good, as it provides all the namespacing benefits of URIs. But the xAPI spec allows anything in stateId and profileId, and, notably, cmi5 uses non-URI values.

How best to allow that? Do we allow that (probably)?

**Comment by garemoko** [comment]
I think we have to allow it because cmi5 but we should definitely discourage it.

**Comment by fugu13** [comment]
One option: have it be @id by default, but have an additional field, which, when specified, is used instead of @id. That way the path of least resistance, just putting in an @id and using that, is the preferred path, but there's a way to model cmi5

**Comment by fugu13** [comment]
Just wanted to capture the discussion we had on this in the meeting a week ago: some were tentatively against adding the short ID, instead preferring consistency of using ID, as URIs are much better identifiers when there needs to be nonconflicting interoperability. Others were tentatively for including them to accommodate current practice.

**Comment by fugu13** [comment]
Consensus, with light disagreement from @garemoko but being okay with it, is don't allow short IDs.
