### ISSUE TITLE
Expectations of LRS/LRP/profile authors

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xapi-profiles#130]
While this issue in general a best practice around requirements, one place where guidance for each role is sorely needed is in patterns:

"In the event two or more statements have identical timestamps, any order within those statements is allowed. “

**Comment by fugu13** [comment]
Regarding the example, we can definitely provide some recommendations for LRPs (There's nothing to say for profile authors there, of course). Are there any other areas you'd like to see these that come to mind?

**Comment by fugu13** [comment]
I believe the specific example is handled now

**Comment by fugu13** [comment]
More generally, I think this is handled across the structure document (the communications document will be tackled following the structure document)
