### ISSUE TITLE
Implied Patterns, AllowedSolo Behavior and Rename

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xapi-profiles#131]
The whole concept of Implied patterns needs to be introduced more clearly.  Start with the benefits.  The field "AllowedSolo" needs a rename, it shouldn’t be about if it is “allowed to be alone”, it should be about if a Statement Template is more than just a Statement Template and why that is something desirable.

**Comment by fugu13** [comment]
Do you have any suggestions for the name? Only reasonable variants I'm coming up with are minor extensions, such as "allowedAsSoloPattern".

**Comment by fugu13** [comment]
`standalone` is a suggestion

**Comment by garemoko** [comment]
Related: I'm suggesting getting rid of AllowedSolo here: https://github.com/DataInteroperability/xapi-profiles/issues/165

**Comment by andyjohnson** [comment]
I'm fine closing this as I agree with @garemoko in removing it.
