### ISSUE TITLE
check for lowercase must and should

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#135]
These can be confusing and it's better to pull them out as specific requirements or use another term. 

One example: "The serialized JSON form of an xAPI Profiles 1.0 profile version must be consistent with what would be produced by the standard JSON-LD 1.1 Processing Algorithms and API Compaction Algorithm using, at least, the normative JSON-LD @context definition provided."

If this particular example is a requirement, it should be broken up into two, the second one addressing the use of the @context definition.

**Comment by fugu13** [comment]
Done in #188
