### ISSUE TITLE
Unclear requirement

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#137]
> All properties that are not JSON-LD keywords (or aliases thereof) in profile documents MUST expand to absolute IRIs during processing as defined in the JSON-LD specification.

The term 'profile document' used in this requirement does not appear anywhere else in the spec. I assume it just means "profile" (or "profile version", see  #134) 

If it does mean "profile", then I'm not clear how it relates to the next requirement:
> All properties that are not JSON-LD keywords (or aliases thereof) in a profile MUST be described by this specification or be expressed using compact IRIs.

They seem to contradict?

**Comment by garemoko** [comment]
I'm now wondering if "profile documents" means json structures defined for use within the xAPIs Document APIs. If so, maybe that requirement should be moved to a section relating to Document API JSON documents?

**Comment by fugu13** [comment]
Just an inadvertent typo, it just means profiles. It doesn't contradict, the first requirement is about not using properties that turn into "blank properties" on expansion, and the second requirement is about the form of the property names that can be used
