### ISSUE TITLE
Add links to terms defined in other specs

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#139]
E.g compact IRIs should link to https://www.w3.org/TR/json-ld/#compact-iris

**Comment by garemoko** [comment]
"Language map" should link to xAPI presumably, which would make clear that the same rules apply (e.g. plain text).

**Comment by garemoko** [comment]
Related to #60

**Comment by fugu13** [comment]
Strangely, language map here (while functionally identical to in xAPI) is actually something in JSON-LD (fortuitous!). But explaining that is good.
