### ISSUE TITLE
define 'matching'

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#140]
In the section 'Using Profiles in Statements' it's unclear what the adverb "matching" means. 

The process of matching is explained somewhat here: https://github.com/DataInteroperability/xapi-profiles/blob/master/xapi-profiles-spec.md#statement-templates

But
1. It would be good to have a separate section explaining about matching and the concept of "determining properties" and
2. It would be good to link to that section whenever we talk about matching.

**Comment by fugu13** [comment]
Reviewing the current text I'm going to close this one, I think things read pretty well currently
