### ISSUE TITLE
suggested new text for profile.definition and  profile.seeAlso

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#144]
The profile definition property should be marked as optional, with a note that it must be included if no seeAlso is provided. Or if we want to keep it required, we should make clear that when a seeAlso URL is provided, the definition should be a shorter plain text summary. 

For seeAlso...

> _Optional._ A URL containing information about the profile. Recommended instead of especially long definitions.

Change to...

> _Optional._ A URL containing human readable information about the profile. Recommended instead of especially long definitions, and for definitions including formatting.

**Comment by fugu13** [comment]
I think we want at least a brief description of the profile in-document, but agreed on clarifying best practice alongside seeAlso
