### ISSUE TITLE
Use of the term "Author" for the Profile Spec

### ISSUE THREAD

**Issue by jhaag75** [adlnet/xapi-profiles#15]
“This specification describes how to author an xAPI Profile.” This is the first sentence of the doc. Perhaps we should change this from “author” to “represent” or “publish” or something else? We will develop tools for people to publish profiles, but we don’t want them to manually “author” anything in RDF/JSON-LD on their own. The way the word author is used here seems to imply they will be expected to manually create these files themselves, which isn’t the case. That would result in a lot of errors, typos, human errors, etc. “Author” is used in second sentence as well. Pretty much anywhere we say “author” we should come up with a more representative term. I know this is somewhat explained later when talking about a “profile” server’s capabilities. But I’m not fond of the term, “author” in this context. We can discuss this further if you guys feel there is a good reason to stick with this term. The only exception is that it seems to make sense to use the term “author” when referring to the provenance metadata of the profile (the creator or author).

**Comment by garemoko** [comment]
I don't think the term author implies writing JSON directly rather than using a tool to do so. Especially since L&D has "rapid **authoring** tools" that enable us to author e-learning without writing code.
