### ISSUE TITLE
re-order properties in Verbs, Activity Types, and Attachment Usage Types table 

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#151]
The current order:

- broader
- narrower
- broadMatch
- narrowMatch
- exactMatch
- relatedMatch
- related

We could either group all the "Match" properties together or alternate them.

**Comment by fugu13** [comment]
I think alternated, so that "used all the time" properties are up top and the "used mostly with deprecation and other funky situations" properties are down below.
