### ISSUE TITLE
Add 'exact' property to core concepts. 

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#152]
**Use case**
You need to change an IRI used in your profile for some reason (a technically important, offensive or embarrassing typo, some ip/copyright issue, moving domain, merging two or more profiles). 

In that scenario you might release a version of your profile that includes the old concept(s) as deprecated alongside the new concept. In that case, the concepts would be 'exact' of one another.

**Comment by fugu13** [comment]
`exact` would be an addition outside of SKOS for relationships between Concepts, which'd be a pretty big thing to do.

Also, I don't see how it improves UX for people trying to use profiles. If both concepts are present but one is deprecated, and there's a `related` between them, tooling will already be able to tell them they should look at the one without deprecation. And if they're some of the worse things on that list, a profile author should probably remove them without deprecating in advance, so anyone using an updated version of the profile wouldn't even see them as options (and the cross-version relationships would apply).

**Comment by fugu13** [comment]
Pending a use case, closing this
