### ISSUE TITLE
Proposed new text for LRP extension requirements

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#156]
Current text:

> Learning Record Providers MUST, for xAPI Statements using Extensions defined here, follow the following rules:
> 
> * a ContextExtension MUST only be used in context
> * a ResultExtension MUST only be used in result
> * an ActivityExtension MUST only be used in an Activity Definition.

Proposed text:
> #### Learning Record Provider Requirements
> 
> * Extensions conforming to a profile MUST be used within the part of xAPI statements they are intended for use within:
>      * Extensions defined with @type `ContextExtension` MUST only be used in context
>      * Extensions defined with @type `ResultExtension` MUST only be used in result
>      * Extensions defined with @type `ActivityExtension` MUST only be used  in an Activity Definition

Markdown:
```
#### Learning Record Provider Requirements

* Extensions conforming to a profile MUST be used within the part of xAPI statements they are intended for use within:
      * Extensions defined with @type `ContextExtension` MUST only be used in context
      * Extensions defined with @type `ResultExtension` MUST only be used in result
      * Extensions defined with @type `ActivityExtension` MUST only be used  in an Activity Definition
```

**Comment by fugu13** [comment]
This phrasing is extremely awkward:

> Extensions conforming to a profile MUST be used within the part of xAPI statements they are intended for use within

I also think using "a Type" is much easier to read (and is a broad standard for how to talk about things in the JSON-LD and RDF worlds) than "defined with @type Type".

What about:

Learning Record Providers MUST only use:
* a ContextExtension in a Statement's context
* a ResultExtension in a Statement's result
* an ActivityExtension in an Activity Definition in a Statement

**Comment by garemoko** [comment]
:+1:

**Comment by fugu13** [comment]
This actually ended up being somewhat different in-text due to some other changes, go ahead and take a look there to see if that works for you
