### ISSUE TITLE
Require use of either scheme or inlineSchema for Document resource concepts where the contentType is application/json

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#159]
I contend that without a defined schema, the Document Resource concepts serve limited purpose. Knowing the IRI of a document isn't much use if you don't know how to write or read the data it contains.

**Comment by fugu13** [comment]
There are lots of useful JSON formats that are exceptionally hard (or impossible? I'm not sure) to write a schema for, but are well defined. For example, JSON-LD documents, which could still include a lot of useful information that can be interpreted semantically.
