### ISSUE TITLE
Not clear what the determining properties are for a template 

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#167]
Based on calls, I know that the following are determining properties for a template. This needs to be clearer in the spec. 

- verb
- objectActivityType
- contextGroupingActivityType
- contextParentActivityType
- contextOtherActivityType
- contextCategoryActivityType
- attachmentUsageType

**Comment by fugu13** [comment]
This is defined in text:

> The verb, object activity type, attachment usage types, and context activity types listed are the determining properties.

We can list them more explicitly and/or rearrange if you think that would help clarity, of course.

**Comment by garemoko** [comment]
I must have missed that text on reading it. So we can either blame me as the read and do nothing, or assume that because I missed it, it needs to be clearer. I'm happy either way.

**Comment by fugu13** [comment]
It's been made more distinctly present in a recent PR if you want to take a look
