### ISSUE TITLE
move section about checking statements to the validation section

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#173]
> When checking previously collected statements for matching a pattern, ordering MUST be based on timestamp. In the event two or more statements have identical timestamps, any order within those statements is allowed. When checking statements for matching a pattern upon receipt, ordering MUST be based on receipt order insofar as that can be determined. If statements are received in the same batch and they are being checked upon receipt, within the batch statements MUST be ordered first by timestamp, and if timestamps are the same, by order within the statement array, with lower indices earlier.

This section is all about validating statements, not the profiles themselves and should be moved to the validation section

**Comment by fugu13** [comment]
Hmm, the greedy part above should probably come along with. In both cases it might be good to drop in some sort of pointer/gloss here so people getting ready to work with patterns are aware of what's going on.
