### ISSUE TITLE
Communication section seems unfinished

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#175]
This section has a few TODOs, questions and notes. It feels unfinished, especially compared to the content above. 

How would people feel about separating out communication and validation as a separate document and then focusing on getting the profile structure definition finished and released before coming back to communication and validation?

**Comment by fugu13** [comment]
I like splitting them up; I think we're likely to end up with both finished (the core of the communication section is pretty much done, since what it's defining is minimal; the TODOs are just odds and ends), but it definitely makes sense organizationally.

**Comment by fugu13** [comment]
(Also, I've done a preliminary split)
