### ISSUE TITLE
Rough Sketch of Example Profile

### ISSUE THREAD

**Issue by jhaag75** [adlnet/xapi-profiles#18]
I noticed all concepts are lumped into a concepts list in JSON-LD. For the vocab spec we have each concept grouped into lists. For example, verbs[ ], activity types [], etc. For an example, look at the current video vocab/profile JSON-LD doc: http://xapi.vocab.pub/datasets/video.jsonld. Would there be any benefit to keeping that same  granularity of list concepts or is it better to lump everything into general “concepts”?

**Comment by fugu13** [comment]
I suspect for presentation they'll often end up being separated or grouped, but I ended up putting them together in the JSON because that flows better with how JSON-LD and the underlying RDF work. Since they're fully typed, presentation layers can easily separate them for display.
