### ISSUE TITLE
Patterns Unclear, May Need Rework/Expansion

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xapi-profiles#182]
I've looked at the example patterns for cmi5 and my intentions of using them were quite different from what was presented.  This could be me not understanding what their intention is.  I wrote some "rules" for patterns of Statements to follow, but rather than focusing on what a pattern SHOULD/MUST be, I was focusing on what it SHOULD NOT/MUST NOT be.  For example, in cmi5, I don't want to allow a "Terminate" and "Abandoned" before an "Initialize".  I feel like I need to build the entire "state space" up rather than list exceptions for it.  The problem with this strategy is that one change to that space could cause a vastly different way of how all of the "allowed" patterns fit together.  I'd rather use exceptions as a filter and let the state space be the rest.  This may be as simple as allowing a pattern to be tagged as "not allowed", but I also don't know anything about the spacing of patterns.  How do I distinguish between allowing zero Statements between an "Initialize" and "Terminate" versus allowing anything in between, so long as the "Initialize and Terminate" are in order?

Sorry for the wall of text.  I've been thinking of patterns as conformance requirements rather than suggestions.  If this line of thinking is off, let me know.  I have a couple more granular issues that feed into this larger issue, but will separate them out.

**Comment by fugu13** [comment]
Patterns are conformance requirements. There's been a lot of research done on how to express possible allowed orderings of things, and the EBNF that's been adopted for Patterns is a very widely used and flexible model with a sound theoretical basis.

There will always be different ways to conceptualize patterns of statements. Trying to provide technical support for using any of them at all would be a very bad idea. No matter what, people using one way to conceptualize Patterns have to map how they're thinking onto another way to conceptualize Patterns.

The way we've got currently is provably comprehensive over all non-ambiguous sequences*, fully described algorithmically with extensive testing, and only takes time proportional to sequence length and pattern size to process (meaning there's no way to attack an LRS by sending a specially crafted sequence that uses a huge amount of processing) and uses an approach familiar to most people with experience using technical standards.

*(that are context-free, which is considered a good property in grammars, and where the contents of a repeating element are not the prefix on any possible following element, but this is a trivial exclusion)

**Comment by andyjohnson** [comment]
One key that is missing for me is the answer to the question above.  What is the implied spacing between the members of a sequence - 0 or any number?

**Comment by fugu13** [comment]
I don't understand what you mean by spacing between members of a sequence -- there is no spacing. The templates/patterns within a sequence are expected to come in exactly that order within a registration. Note that statements not within the registration are irrelevant to the pattern for the registration.

**Comment by andyjohnson** [comment]
We talked through this well on the call.  There are benefits to expanding, but that can be a future consideration.  As you said, @fugu13 , if cmi5 had been created AFTER the profile spec, things likely would be much different.  We are seeing these two collide in ways future profiles shouldn't.  I am fine closing this/moving to future version.
