### ISSUE TITLE
Recommend adding "exactlyOne" rule to Patterns

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xapi-profiles#183]
cmi5 in particular has a lot of expectations that a value/type of Statement is sent only one time.  I think having a check to see if it is within a pattern, but only one time, would be valuable.

**Comment by fugu13** [comment]
cmi5 has no varieties of statement that are only one time within a given registration. A registration in cmi5 is for an entire course, and all the only one time requirements cmi5 has are for a given AU, which there may be multiple of within a course (and thus registration).

There's some potential for a "possibly in multiple places, but only once" marker (though it wouldn't do anything for cmi5, at least unless we made it a lot more complex, like involving a JSONPath value that had to be unique, etc), but both 1) that can also be expressed by making the pattern have alternates of sequences for each possible slot of the one value and 2) having a bunch of statements that can be sent at basically any time but only once as part of a single registration is probably not something that should be encouraged.

**Comment by andyjohnson** [comment]
Not sure where the registration is coming from, I'm talking about within a session of one AU for many of the cmi5 cases.  Session being between a "Launched" statement and a "Terminate/Abandoned" Statement.  Again, with my overall confusion on patterns, I could be missing something here.

**Comment by fugu13** [comment]
Yes, what I'm saying is you can't restrict any statement templates to exactly one within a registration, which is the model of the profile spec, because within a registration there are no cmi5 statements restricted to exactly once.

**Comment by andyjohnson** [comment]
As we talked about on the call, I'm okay with bumping this to a future version consideration.
