### ISSUE TITLE
Clarity/Question in Selector

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xapi-profiles#184]
When using Selector, how do I search for more than one item that ends up making a "key"?  The use case I have is for cmi5, I only care about restricting the set of Statements that are for a particular Actor in a particular Object (activity), such that these make up a unique pair that I can verify patterns against.  If I do a wild card on both, do I get all of both sets, or will it iterate over each pairing?

**Comment by fugu13** [comment]
I don't really understand what you're trying to do. Could you make your example more concrete?

**Comment by andyjohnson** [comment]
Sure, lets say there is a Biology 101 Course that contains multiple activities, including an Introduction to Photosynthesis.  Actor "andy" is registered for that course.  I want to do a search on all Statements for Actor "andy" and on activity "Introduction to Photosynthesis" and verify that there are not 2 "Completed" Statements within that set.

**Comment by fugu13** [comment]
Statement Template rules are about the forms of individual statements. They have nothing to do with sets of statements.

**Comment by andyjohnson** [comment]
We handled this on the call pretty well.  Where some of my confusion came from is that it wasn't obvious to me that a JSONPath String was more than just a datatype, that there is logic built into it.  Steps have been made to make this more obvious, so you can close this issue as far as I'm concerned!
