### ISSUE TITLE
Add best practices on profile version URI construction

### ISSUE THREAD

**Issue by fugu13** [adlnet/xapi-profiles#2]
A short note should help people make good URIs for versions.

**Comment by garemoko** [comment]
Possibly a separate issue, but certainly related: it should be made clear that version URIs are specific to the profile AND the version, not just the version. e.g. https://base-profile-uri/version-number

**Comment by jhaag75** [comment]
I feel this should be handled transparently using the authoring/publishing tools we create based on the profile spec. It should not be left to people. Just introduces more potential for errors. But we do need some short notes or examples in general or at least need to discuss.

**Comment by fugu13** [comment]
I think this is best done in another document; closing
