### ISSUE TITLE
term "producer" is not defined

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#21]
https://github.com/DataInteroperability/xapi-profiles/blob/master/xapi-profiles-spec.md#using-profiles-in-statements

The term "producer" is not defined, but from the context I assume this refers to what xAPI calls a Learning Record Provider or LRP. If that's right, let's use the same term as xAPI.

**Comment by fugu13** [comment]
Yeah, this is just quick-typing that needs fixing up rather than an intent to introduce a new term. There're a lot of little things like that in here, it is intentionally a very rough draft.

**Comment by garemoko** [comment]
Cool. Not judging, just issue raising :-) I'll keep noting what I see so we can fix them.

**Comment by aaronesilvers** [comment]
+1 Andrew. Keep going :)
