### ISSUE TITLE
Updated Definition

### ISSUE THREAD

**Issue by jhaag75** [adlnet/xapi-profiles#220]
@fugu13 @garemoko

I didn't see a formal definition in the spec updates. There is improved readability and descriptions of the spec in general, but would like to see a formal definition of profile as well. We had an issue open previously that was closed #142 , but I don't believe we ever decided on a formal definition. 

The formal definition we were previously using was, "“A profile is a specific set of rules and documentation for implementing xAPI in a particular context. Profiles generally provide a particular vocabulary of terms, some created specifically for the profile, and some are referenced from other vocabularies.”

Based on the new profile spec, I propose the following (leaner) definition:

"A profile is both the human and machine-readable documentation of application-specific concepts, extensions, statement templates, or other data used when implementing xAPI in a particular  context."

**Comment by fugu13** [comment]
@jhaag75 the definition of profile is given in the definitions list, here: https://github.com/DataInteroperability/xapi-profiles/blob/master/xapi-profiles-about.md#profile

The current text, which I think you'll find aligns pretty well with yours, is:

> What this specification focuses on. A way to talk about Concepts, Statement Templates, and Patterns for Experience API data, and in particular to describe them so machines can do some processing automatically.

I'll go ahead and add "in a particular context" after "data".
