### ISSUE TITLE
Add definitions for/introductions to SKOS and PROV

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#23]
Since SKOS and PROV feature a few times in the document, it would be helpful to add some short definitions of each and their relevance for those not familiar with them. This is started in [Technical Foundations](https://github.com/DataInteroperability/xapi-profiles/blob/master/xapi-profiles-spec.md#technical-foundations) but more detail would help.

**Comment by jhaag75** [comment]
We have some of that intro SKOS already in the vocab spec here: https://adl.gitbooks.io/companion-specification-for-xapi-vocabularies/content/dataset_schema_design/alignment_with_skos.html

I thinkt the Primer talks about use of PROV too.

I think we might consider merging the vocab spec & primer with the profile spec at some point...they are essentially proposing the same approach to modeling/structuring the data.
