### ISSUE TITLE
ObjectActivityType is an IRI, not an Object

### ISSUE THREAD

**Issue by deathtenk** [adlnet/xapi-profiles#238]
Filing an issue about the **xAPI Profiles** specification? Please include the following

- [ ] Which part/parts of the specification are at issue?
The documentation

- [ ] What is your understanding of what the spec means in these parts?
The ObjectActivityType under StatementTemplate is defined as an Object in the spec [documentation](https://github.com/adlnet/xapi-profiles/blob/master/xapi-profiles-structure.md#80-statement-templates) however it's actually an IRI.

- [ ] Related to your implementation, what's the use case you're trying to achieve? What are the user stories you're trying to support?
Not applicable

- [ ] How you would like the specification to be improved?
Just a minor typo in the documentation.

**Comment by fugu13** [comment]
Good catch, will fix

**Comment by fugu13** [comment]
Change made, new release made
