### ISSUE TITLE
Organizations and Persons

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#24]
Needs some explanation before or after the table as to what this is.

**Comment by jhaag75** [comment]
Agree. I was going to ask about this one as well. Should we use FOAF here for the @type?

**Comment by fugu13** [comment]
This is for who creates profiles; this may end up FOAF, or it may end up schema.org

**Comment by garemoko** [comment]
Do we need this? Why?

**Comment by fugu13** [comment]
So people can tell (and tools can tell them) who wrote a profile

**Comment by garemoko** [comment]
Ok. This has my blessing. :-p
