### ISSUE TITLE
Under active development?

### ISSUE THREAD

**Issue by ghost** [adlnet/xapi-profiles#241]
I'm making an assumption, but it seems like this repository is being superceded by https://github.com/adlnet/xapi-authored-profiles. I'm assuming that now b/c the last commit was almost over 6 months ago. Could you clarify please, the relations between the two repositories?

**Comment by FlorianTolk** [comment]
This is the spec for making xapi profiles, while [https://github.com/adlnet/xapi-authored-profiles](https://github.com/adlnet/xapi-authored-profiles) is a list of authored profiles.

**Comment by ghost** [comment]
So these specs are now stable?

**Comment by andyjohnson** [comment]
In terms of stability, the profile spec is really still being tested in the community, while the authored profiles have a wide variance in degree of adoption.  I would recommend looking at each group's work individually.  ADL will be doing more with the profile spec in terms of aiding adoption and mapping it to previously authored profiles in the coming year.
