### ISSUE TITLE
Typo within Section 6.2 Organizations and Persons

### ISSUE THREAD

**Issue by FeLungs** [adlnet/xapi-profiles#249]
Filing an issue about the **xAPI Profiles** specification? Please include the following

- [ ] Which part/parts of the specification are at issue?
2.6
- [ ] What is your understanding of what the spec means in these parts?
definition of the profile author as an individual or organization
- identified by URL with name as a label
- type indicates if the URL + Name describe an individual or an organization 
- [ ] How you would like the specification to be improved?
The type property has a type of object when it should be string
- takes the value of either "Organization" or "Person"

**Comment by garemoko** [comment]
![image](https://user-images.githubusercontent.com/1363163/59158406-8e22ca80-8ab1-11e9-8995-e7ee166e12c6.png)

+1 good catch. This should be changed to "String"

**Comment by jhaag75** [comment]
It's an object. It has a property called "name" that is a string.

https://schema.org/Organization

**Comment by garemoko** [comment]
@jhaag75 Isn't this table the description of the organisation object though? The property name "type" and description seem to suggest that this property is a string, as does the fact that there is a name property already. This structure seems unlikely to be intended:

```
{
  "type": {
    "name": "Andrew Downes"
  },
  "name": "Andrew Downes"
}
```

**Comment by jhaag75** [comment]
I didn't provide enough info. Sorry about that. We are talking about author
here (which is defined by https://schema.org/author). It's type is the
value of either the "Organization" or "Person" objects, not just any string
value.

Organization has these properties:
https://schema.org/Organization

Person has these properties:
https://schema.org/Person

If you take a look at Section 6.0, for "author" that's where this is coming
from. It's listed there as an object. These are actually schema.org objects.

The mapping of these to schema.org is in profile-context.jsonld:

https://github.com/adlnet/xapi-profiles/blob/master/context/profile-context.jsonld

**Comment by garemoko** [comment]
Right, but "Organization" and "Person" are strings, not an objects.

**Comment by jhaag75** [comment]
Oh I see now. I did not see that table displayed when reading this via
email and misunderstood the question. That should be a string.

**Comment by andyjohnson** [comment]
Per the 7/19/2022 meeting, feel free to add to/create a PR for this
