### ISSUE TITLE
Fix Type for optional, oneOrMore and zeroOrMore in Patterns Table

### ISSUE THREAD

**Issue by FeLungs** [adlnet/xapi-profiles#250]
Filing an issue about the **xAPI Profiles** specification? Please include the following

# Which part/parts of the specification are at issue?

**`type` column value for `optional`, `oneOrMore` and `zeroOrMore`**

![Screen Shot 2019-11-20 at 15 11 26](https://user-images.githubusercontent.com/16762375/69274473-68453a00-0ba8-11ea-9789-d2fc11c69c9f.png)

Given above, `optional`, `oneOrMore` and `zeroOrMore` must be defined as
- `{"id": "Pattern URI" | "Template URI"}`

but `alternates` and `sequence` must be defined as
- `["Pattern URI" | "Template URI", "Pattern URI" | "Template URI", ...]`

ideally, all pattern items should be either a `URI` or an `Array` of `URI`
- no need to wrap the single `URI` in an `Object` when the only field  is `id`
  - doesn't add any additional information
- alignment with examples in the spec
  - see screenshots below

# What is your understanding of what the spec means in these parts?

**Reference to "A single Pattern or Statement Template identifier"**

`oneOrMore`
![Screen Shot 2019-11-20 at 15 14 50](https://user-images.githubusercontent.com/16762375/69274559-99be0580-0ba8-11ea-893d-ea77f01c7e90.png)

`zeroOrMore`
![Screen Shot 2019-11-20 at 15 15 57](https://user-images.githubusercontent.com/16762375/69274610-b5c1a700-0ba8-11ea-9fae-37e9d925754c.png)

# Related to your implementation, what's the use case you're trying to achieve? What are the user stories you're trying to support?

Removal of unnecessary `Object` container

# How you would like the specification to be improved?

**Replace `object` with `URI` for `optional`, `oneOrMore` and `zeroOrMore`**

| Property | Type | Description | Required |
| --------- | ----- | ----------- | --------- |
| optional | URI | ... | ... |
| oneOrMore | URI | ... | ... |
| zeroOrMore | URI | ... | ... |

@aaronesilvers, @andyjohnson this issue relates to validation of xAPI Profiles against the spec.
- Correction of the inconsistencies will reduce confusion for
   - Spec readers
   - Profile Authors
   - Profile Validation devs

**Comment by creighton** [comment]
Agree they should be URI, also note the description for the id field should say "A URI for the Pattern"

**Comment by andyjohnson** [comment]
Per the 7/19/2022, group agrees- feel free to throw a PR at this (or I could too)

**Comment by andyjohnson** [comment]
Per the 7/19/2022 - would like to see some solid pattern examples with some logic/flow graphical support

**Comment by andyjohnson** [comment]
Per the 7/19/2022 - can use https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/ to create flow within Markdown
