### ISSUE TITLE
Unable to access ADL's Profile Server at http://xapi.vocab.pub

### ISSUE THREAD

**Issue by ranaalisaeed** [adlnet/xapi-profiles#251]
Hi
I'm not sure if this is the right forum to ask this question. The ADL's Profile Server, http://xapi.vocab.pub mentioned at various places in this spec is not reachable. I'm trying to access it from Australia. Is this URL still active?

**Comment by andyjohnson** [comment]
The new URL is profiles.adlnet.gov - there have been redirects in place, but the server was down so often that they didn't always work.
