### ISSUE TITLE
Use prefDisplay and altDisplay instead of prefLabel and altLabel

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#26]
in xAPI verbs have a display property for their human readable component. Activity types and attachment usage types have no human readable component. 

For consistency with xAPI I think we should stick with display instead of label.

**Comment by fugu13** [comment]
prefLabel and altLabel are what they're called in SKOS, and my default was to use the terms like in the original sources unless there was an overriding reason not to, but I'm totally fine with switching to prefDisplay and altDisplay if people would prefer that.

(this is just a JSON-LD display issue; in SPARQL queries people will need to use the underlying RDF term)

**Comment by garemoko** [comment]
Let's talk about this one on a call.

**Comment by jhaag75** [comment]
I think it would help to keep things consistent with core spec. So we could define these as our own properties in the xAPI ontology and make them subproperties of prefLabel and altLabel, right?

**Comment by fugu13** [comment]
@jhaag75 most likely we'd just use JSON-LD names of prefDisplay and altDisplay that still translated into skos:prefLabel and skos:altLabel in RDF

**Comment by fugu13** [comment]
Any new opinions on this? Rough consensus before was to keep prefLabel and altLabel.

**Comment by fugu13** [comment]
Closing since consensus was to keep and no new input
