### ISSUE TITLE
Should Google Group with GoToMeeting link be archived?

### ISSUE THREAD

**Issue by BrendaBraitling** [adlnet/xapi-profiles#266]
Filing an issue about the **xAPI Profiles** specification? Please include the following

- [README.MD Is the google group still active?  ] Which part/parts of the specification are at issue?

- [ The Readme is orienting people to the work and the team] What is your understanding of what the spec means in these parts?

- [For the Readme I would like to assure that interested parties are directed to current work efforts ] Related to your implementation, what's the use case you're trying to achieve? What are the user stories you're trying to support?

- [ Please archive old information for historical context and update to current working group and/or maintenance group information] How you would like the specification to be improved?

**Comment by imartinezortiz** [comment]
@andyjohnson seems to me that this has been already addressed in the #280 that is already merged in the repo. Can you close the issue ?

**Comment by andyjohnson** [comment]
Yes, agreed.  Closing the issue.
