### ISSUE TITLE
deprecated URIs

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#28]
Deprecated URIs shouldn't happen, but have and will happen. 

It would be good to have a way for a profile to identify URIs that a LRP implementing a profile shouldn't use, but which a LRC reading statements conforming to profile (possibly including earlier versions) will need to support.

**Comment by fugu13** [comment]
One, I think adding a deprecation property is definitely a good idea.

Two, I think a good approach for your scenario is define a first version of the profile with the old URIs, already marked as deprecated, then define a new version of the profile with the new URIs (and the appropriate relations, notably exactMatch from the new URIs to the old URIs). Then anyone still using the old ones can use the old version, but authoring tools and such will hopefully clearly note deprecation, and everything's able to easily discover both the current preferred terms and their connections to the old terms.

**Comment by garemoko** [comment]
Reading about 'exactMatch' was what inspired this thought, but that's specifically for "other profiles". Do old versions count as other profiles? Or do we need an "exact" property?

**Comment by fugu13** [comment]
Yeah, another version would also be when the *Match options would be used, though between versions of the profile only exactMatch and maybe relatedMatch should be used.
