### ISSUE TITLE
Activities section needs attention

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#32]
I don't think we should re-define activities here. We should just reference the xAPI spec. 

Is there any particular desperate need for adding the @ in front of the id?

**Comment by fugu13** [comment]
Strangely, there is a need for the @id. We'll... probably? definitely? need to include an @context as well. And it could get complicated with extensions, though I've got some ideas. JSON-LD really really likes to know every property being used.

I definitely don't want to redefine activities, the main reason for listing the properties is to make clear you can put a whole activity here (and that @id, and @context, are here too despite not normally being in a definition). I'd like to include at least a gloss on the list of primary activity properties, but I agree we don't want to redefine activities.

**Comment by garemoko** [comment]
What if we reference the activity section of xAPI and then have a table of additional properties? 

That would potentially mean having @id and id properties, although we could specify that @id replaces id?

**Comment by fugu13** [comment]
Yeah, the rule (that just isn't full written down yet) would be that the Activity must have an id matching @id, and that the entire definition is included or no definition is included, and that @id and @context are not part of the definition. There might need to be some requirements about including extension @contexts in any complex-valued extensions to make everything work nicely with JSON-LD too, but those could be included in the definition at no detriment.

**Comment by garemoko** [comment]
Why does the entire/no definition need to be included? What about language maps?

**Comment by fugu13** [comment]
The entire/no is basically to prevent data issues; if a system sees an activity that is canonically controlled it should either not see the definition (perhaps filling it in from elsewhere) or see the whole definition. Good point that changes to languages in language maps (including just one, including one not in the definition, etc) should be okay.
