### ISSUE TITLE
dependent rules for statement templates

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#37]
edit: original text is preserved, but see discussion for how this moved to being about dependent rules for statement templates 

The descriptions for the any and all statement template properties are not clear. We also need examples. My understanding from the descriptions is that this is a value statement template:

```
"requirements": [
    {
        "location": "context.contextActivities.grouping[0]",
        "rule": "included"
    },
    {
        "rule": "included"
        "any": [
            {
                "location": "result.score.scaled"
            },
            {
                "all": [
                    {
                        "location": "result.score.raw"
                    },
                    {
                        "location": "result.score.min"
                    },
                    {
                        "location": "result.score.max"
                    }
                ]
            }
        ]
    },
    {
        "any": [
            {   
                "rule": "included",
                "location": "object.definition.name"
            },
            {   
                "rule": "excluded",
                "location": "object.definition.description"
            }
        ]
    }
]
```

Note the placements of the rule properties in the above. Should we require the rules to always be on the same level as the related location property?

**Comment by fugu13** [comment]
This is not what the syntax for statement templates is. any and all are defined to be arrays of values, not of objects with rules and locations. For example, to express that all actor members must have accounts, and they must be on a particular domain:

```
{
    "location": "actor.member[*]",
    "selector": "account.homePage",
    "all": ["http://homepage.sso.example.com"]
}
```

Or to express that at least one grouping context activity must have one of two activity types:

```
{
    "location": "context.contextActivities.grouping[*].definition.type",
    "any": ["http://xapi.example.com/type1", "http://xapi.example.com/type2"]
}
```

(note to self: make it so statements using profiles _must_ use the array context activities syntax)

**Comment by garemoko** [comment]
Oh I see. 

Well, do we need a way to say that you must include either a raw or a scaled score? Or that if you included a activity definition name you must also include a description?

**Comment by fugu13** [comment]
Either a raw or a scaled score can be done pretty simply, but "if you included a activity definition name you must also include a description" -style dependent rule is currently not possible. (That particular example is one I'd argue vehemently against ever actually doing, but the general idea of value dependency is at least a semi-reasonable thing -- whether it is worth the much increased complication is a different question; I'd lean toward no).

**Comment by garemoko** [comment]
Yeh, they were just the first properties I thought of, rather than real examples. 

I guess the "this OR not that" could possibly be achieved by multiple similar templates, one for 'this' and one for 'not that'. The pattern `alternatives` property could then be used to make it a choice between the two.

**Comment by fugu13** [comment]
Hmm, that wouldn't be possible because the way statement templates are written, if the determining properties match a statement, the rules *must* match, and there are some pretty big advantages to that. I think we'd want to do dependent properties another way -- if we can find a solid use case. Everything I can come up with is pretty contrived, and feels very "fragile".
