### ISSUE TITLE
Use of index for array properties in statement template location

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#38]
```
"requirements": [
    {
        "location": "context.contextActivities.grouping[0]",
        "rule": "included"
    }
]
```
The example given seems to saying that we can use the index of arrays to require index + 1 items to be included in that array. If that's the case, we should make that clearer.

We should also make clear that the order of context activities is important when following profiles, for example a profile could theoretically require the first grouping to exclude a particular extension and the second one to include it.  Or, if it's not intended that order is important, we should change how we handle arrays to make that not the case.

**Comment by fugu13** [comment]
> The example given seems to saying that we can use the index of arrays to require index + 1 items to be included in that array. If that's the case, we should make that clearer.

It's a natural consequence of the logic, but it isn't some special rule, just one of many things that can be expressed naturally. We could certainly mention it.

The order of things in arrays can be left to matter, or things can be expressed order independent (such as that at least one grouping context activity needs a particular extension; that would be easy enough to express). There are some edge cases we'll want to explore (like making sure we can express some activity in context activities needs to have both a particular activity type and a particular extension... I'll think about that one), but the templates are already very powerful while remaining concise.

**Comment by fugu13** [comment]
I think this can be closed what with the examples and so forth.
