### ISSUE TITLE
alignments and statement references sections need tidy up

### ISSUE THREAD

**Issue by garemoko** [adlnet/xapi-profiles#39]
I'd be inclined to delete both because I don't know what alignments are and I don't see why statement references need special treatment.

**Comment by fugu13** [comment]
There're good reasons to give statement references special treatment; specifically, it would be very powerful to be able to describe the patterns of statements to be targeted by statement references in other patterns. But they're so little used I'm inclined to leave that part out to reduce complexity; it can be added if practices emerge.

Alignments are things like saying, statements matching this template align with (represent experiences working toward) this part of common core. They're a definite need... but not necessarily one that needs to be expressed in profile documents, at least currently.

**Comment by fugu13** [comment]
I think I might actually make an attempt at StatementRefs for the group to consider. I think alignments are clearly out of scope of the direction this is going in.
