### ISSUE TITLE
Granularity/Types of Profiles

### ISSUE THREAD

**Issue by jhaag75** [adlnet/xapi-profiles#45]
In issue #17 (closed) I pointed out we need more clarity on the difference between vocabulary and profiles (or merging them into a single concept of profiles as Russell proposed). However, we also need to determine the level of granularity allowed for profiles (or clearly specify the different types of profiles supported in xAPI). I'll try to explain in bulleted sections below.

1) First let's talk vocabulary vs profile. ADL created a vocabulary list (https://w3id.org/xapi/adl), and it also has a specific profile (SCORM) that uses the vocabulary. The SCORM profile (https://w3id.org/xapi/scorm) also defines additional types of properties that are used specifically in that profile. The SCORM profile exclusively uses the ADL vocabulary terms but also defines additional custom data elements within the profile to address concepts unique to SCORM (e.g., attempt state, temporal model). Another example of this is [medbiquitous](https://w3id.org/xapi/medbiq). They have a core vocabulary list of terms they plan to add to, but plan to build out several different profiles over time based on their various medical scenarios or use cases. The have already built one ([virtual patient](https://w3id.org/xapi/medbiq/virtual-patient)), but anticipate the need to create additional profiles in the near future. So my question here...isn't there a need to have vocabularies and profiles as separate datasets? If we merge them together conceptually then it opens up more questions on how to deal with the current ADL & medbiq vocab terms as well as older xAPI terms and old practices from activity streams, tincan, etc. For example, if we merge the ADL vocab and SCORM profile together then are we saying that ADL terms are only skos:inScheme of the SCORM profile? If so, that's fine we just need to figure how to handle all of the older IRIs and associate them with certain profiles. It also might impact  IRIs and content negotiation. For example, if you GET the SCORM profile IRI it returns all of the SCORM profile data, not just the vocabulary dataset/list or even the individual terms. 

In addition to distinguishing between vocabularies and profiles there are larger, existential questions about just profiles. See (2) below.

2) What are the different types of profiles? It seems we currently have the concept of what I'm calling a "project profile" that may define a vast amount of custom properties, vocab, and extensions. Project profiles seem to be rather large implementations that are based on other specifications, concepts, or broader use cases. In addition to SCORM, cmi5, IEEE ADB, and Medbiq virtual patient project profiles, another example of a project profile is Across X: https://w3id.org/xapi/acrossx. In addition to these project profiles (e.g., cmi5, SCORM, IEEE ADB, Across X), more granular types of "activity-based profiles" can be created to represent specific implementations of learning activities. For example, activity profiles (e.g., assessment or video) can be used as a stand-alone profile or within a broader project profile. This is similar to the granularity that IMS Caliper is attempting to achieve where they have the concept of "metric profiles" for very discrete event-based activities such as posting or interacting with a discussion forum, media (audio/video), etc. These metric profiles can then be reused inside of any type of implementation. I think it's important that we recognize the potential levels of granularity here when talking about profiles. They could be very small reusable profiles or they could be very specific implementations with lots of requirements and not very reusable. Should the more granular types of profiles be activity/event based? Should they only be project / specification based? Or both? Do we need tighter control / governance over granular profiles (those that have the most reuse potential)?

3) I'm not sure "project profile" vs "activity profile" is the best way to describe these. Any thoughts on normalizing the terminology and concepts around profiles is much appreciated. It seems like we need to step back and figure this out. It has big implications on how people will understand the importance of profiles, but also will have bigger implications on the interoperability & validation of profile data in general, and also in how we will develop tools to support creating/authoring and publishing profiles.

**Comment by fugu13** [comment]
1. Profiles can be vocabulary-like by being mostly concepts, and the statement templates can refer to terms from other profiles. inScheme is only used in profiles for being a concept in the profile -- terms used across profile are not also inScheme of the profile they're additionally used in.

2. I expect to see some profiles that are more about providing a rich set of constructs and other profiles that are more about setting up communications rules, and every mix in between. I also expect to see smaller more focused profiles as well as larger, expansive ones, and every mix in between.

3. I think the appropriate term for both is profile. I don't see the value in attempting to set up delineations between these, and I see a lot of potential confusion and harm.

**Comment by jhaag75** [comment]
Been meaning to follow up on this. So just so I'm clear on what is being proposed...the new profile spec and the updated example of the SCORM profile looks like you suggest that all of the ADL vocabulary terms should be associated with existing profiles? For example, terms like abandoned and waived should now be associated with the cmi5 profile. And all of the other concepts should associated with the scorm profile? Then we should version out the old ADL vocabulary list. That way everything is connected to a profile. Is that the general idea? I need to make sure we have this right before adding the wrong tool functionality for publishing profile data.

**Comment by jhaag75** [comment]
Therefore, every concept that belongs to a profile should use the "skos:inScheme" property to connect them to the profile. 

What are your thoughts about the referencedBy property we created previously as part of the vocab working group? I see no mention of that being deprecated yet I only see use of skos:inScheme. Can you elaborate on why we still do (or do not) need referencedBy?

**Comment by fugu13** [comment]
@jhaag75 first, re: referencedBy. The use of inScheme here is the same as the use of inScheme you can see in the example vocabularies, for example at https://github.com/fugu13/xapi-vocabulary/blob/master/examples/sports.jsonld#L23 . referencedBy was for a different purpose that is not (currently) possible in profiles, and so isn't present.

Regarding particular vocabulary terms, I see a few possible ways forward for the ADL and its compendium of terms, with the two main ones being:

1. put all verbs and activity types in a profile with no templates or patterns, then just use them in the profiles that have templates and patterns

2. put verbs and activity types that strongly associate with a particular profile (SCORM, mostly) into that profile, and put the rest in a catchall like described in 1.

Either one of these would work fine. In both cases, the descriptions of each profile should probably crosslink to all the other profiles, since people are used to finding all the information together.
