### ISSUE TITLE
Make it possible for profiles to 'comment' on concepts from other profiles

### ISSUE THREAD

**Issue by fugu13** [adlnet/xapi-profiles#57]
Right now, profiles can use other profiles' concepts in their statement templates by specifying the identifiers in various slots, but can't provide additional/suggested metadata. For example: Verb X might only have a prefLabel in English and no altLabels in its original profile, so Profile B might want to 'comment' with altLabels in traditional and simplified Chinese to supplement the lack of multilingual labels.

Do we allow this?

**Comment by fugu13** [comment]
The list of allowed 'commentary' metadata would be limited

**Comment by fugu13** [comment]
Some interest in: single owner, but for non actively maintained profiles allow successor profiles (that can then add additional languages).

**Comment by fugu13** [comment]
Single ownership is preferred, with transfer of ownership for profiles not sufficiently updated.

Side issue: profile server will likely want to require open licensing of profiles.

**Comment by fugu13** [comment]
This issue should be replaced by one describing the needed changes to the spec (largely descriptive) around how new languages for concepts should be handled.

**Comment by fugu13** [comment]
Jason Haag would like to reopen discussion on this, citing AcrossX profile activity in particular and suggesting that profile owners may be slow to incorporate other languages than the ones they include to start with.

**Comment by FeLungs** [comment]
"ADL is building a profile server and will allow for community curation and management of profiles."  I think this server will solve these language concerns.  

Echoing Jason's commented during the call, as long as there is an interface for someone to suggest an addition to a given profile and a way for an admin to review said suggestion before adding it to the profile, we would only run into outdated profiles if they are not hosted on the community server.  This encourages people to use the community server which has many benefits for the community as a whole (reliable source of up-to-date profiles, the ability to easily update profiles, greater sense of community, continuous growth of "official" profiles).

There is obviously the discussion of what the review process looks like for an admin updating profiles or what qualifies you to be an admin but that can be tabled for now.

**Comment by michaelm525** [comment]
I also agree with Jason's concern. If the location of the profile was centralized per @FeLungs comment, it may not be as much of an issue. I think this may be a concern even beyond the language issue for modifications to profiles. If the "owner" of a profile is not responsive enough, this may lead to duplication of efforts and confusion.

**Comment by fugu13** [comment]
Maintaining earlier consensus; new issue opened
