### ISSUE TITLE
Decide what's required in the core URIs for statement templates

### ISSUE THREAD

**Issue by fugu13** [adlnet/xapi-profiles#6]
Is verb required, in particular? If verb isn't included, is object activity type required? And so forth.

**Comment by garemoko** [comment]
I think the way it works at the moment, we'd need to require at least one of verb, activity type or an attachment usage type to be present. 

Related to https://github.com/DataInteroperability/xapi-profiles/issues/8

**Comment by fugu13** [comment]
Now that I've worked through the SCORM Profile, I don't think we can require any particular part, even verb. Closing.
