### ISSUE TITLE
Clarity for "Concepts"

### ISSUE THREAD

**Issue by andyjohnson** [adlnet/xapi-profiles#62]
In the text description of Concepts, it says to use the following terms, but the concept of "Concept" hasn't really been introduced.  By inference it seems we are saying that Concept is a generic term for verbs, activity types, and attachment usage types.

**Comment by fugu13** [comment]
Concepts also include extensions and document resources, and potentially other things with time. It is defined only be usage: things we want to define in a profile that can be reused flexibly in xAPI statements without necessarily conforming to strict usage rules (unless one opts in to statement templates and patterns via using the profile in category).

The usage of concepts is described in the Structure section toward the top of the spec; I see a few things to add there, and I'll capitalize Concepts.
