### ISSUE TITLE
Refine language significantly around statement template rules

### ISSUE THREAD

**Issue by fugu13** [adlnet/xapi-profiles#8]
Right now isn't very clear, though I think the included capabilities are mostly right. Examples will be good.

**Comment by garemoko** [comment]
I duplicated this here: https://github.com/DataInteroperability/xapi-profiles/issues/35. I'll close that and copy the text.

> Which statement template applies is determined by the verb, object activity type, and attachment usage types in the statement. If the verb, object activity type, and all attachment usage type(s) are present and the profile is used as a category context activity, the rules in the Statement Template MUST be followed.

This block, while I like the approach, is confusing to read and seems to be putting the cart before the horse. We should re-word it to make clearer that LRPs generating statements following a profile should follow the templates to determine the identifiers (and other properties) to use, and LRCs reading statements should look specifically to the verb activity type, any attachment usage type(s) and the profile (version) id to determine which template is being followed and validate/process the rest of the statement accordingly. 

We should also state that a profile version MUST NOT have two statement templates that use the same verb, activity type and attachment usage type(s) combination as these essentially act as a composite id for the template in a more real way than the actual id property. Alternatively, we could require the statement template id to be included in statements and expect LRCs to use that to determine which template is being followed.

**Comment by andyjohnson** [comment]
I agree with everything @garemoko says, but I do also want to be clearer that IF ALL of verb, object activity type, and attachment usage type are used, AND the category context activity is populated with the value of the profile, THEN the rules in the Statement Template MUST be followed.

**Comment by fugu13** [comment]
@andyjohnson the language `If the verb, object activity type, and all attachment usage type(s) are present and the profile is used as a category context activity, the rules in the Statement Template MUST be followed.` has been in the spec since the first version (though it needs updating now to include the additional matching rules).

**Comment by fugu13** [comment]
Regarding the issue as raised by @garemoko, I think addressing the LRPs makes sense, I'll make an attempt at it.
