### ISSUE TITLE
Add examples for concepts, templates, and patterns

### ISSUE THREAD

**Issue by fugu13** [adlnet/xapi-profiles#82]
In appendices? Inline? In companion documents with mention in the spec?

**Comment by jhaag75** [comment]
I personally have more preference for inline or in appendices. This might be easier in terms of maintenance. However, we will also need to make similar examples for the profile server. So either is fine really IMO as long as they can be easily edited and added to.

**Comment by fugu13** [comment]
Add example of a "redo" during the recording of a pattern, per @ljwolford
