### ISSUE TITLE
Create and host JSON-LD Context for xAPI Activity

### ISSUE THREAD

**Issue by fugu13** [adlnet/xapi-profiles#84]
And add the URI to the spec in the Activity section

**Comment by jhaag75** [comment]
Do you want to send it to me and I'll post it on the server where all the previous vocab stuff was hosted? 

The old vocab context is here: http://xapi.vocab.pub/vocabulary/context.jsonld

Could post it to: http://xapi.vocab.pub/profiles/context.jsonld ???

**Comment by fugu13** [comment]
@jhaag75 I've picked URIs for the two contexts that need hosting, which can both be found in this repo.

First, https://w3id.org/xapi/profiles/context for the main context.

Second, https://w3id.org/xapi/profiles/activity-context for the activity-specific context.

If you could put them somewhere then hook up the w3id URIs to point to that place, that should complete the release!

**Comment by jhaag75** [comment]
Thank you. Will get to this asap. Traveling at the moment. BTW, what's the
status with the profile ontology?

**Comment by fugu13** [comment]
Oh, heh, forgot to send it. I'll email it shortly.

**Comment by jhaag75** [comment]
ok thanks!

**Comment by jhaag75** [comment]
A PR was sent: https://github.com/perma-id/w3id.org/pull/758

The IRIs will resolve to the new profile ontology and the profile context once both PRs are accepted at both the w3id repo and the adlnet/xapi-profiles repo.

**Comment by jhaag75** [comment]
Question is the activity context specific to the SCORM profile? I thought it was for some reason. If not, I'll set that up as well.

**Comment by fugu13** [comment]
Nearly missed the question here; the activity context is not specific to the scorm profile, every profile including activities needs to use it (as a @context for the activityDefinition element)

**Comment by jhaag75** [comment]
ok thanks!
