### ISSUE TITLE
Add field with profile spec version number to profiles

### ISSUE THREAD

**Issue by fugu13** [adlnet/xapi-profiles#86]
Since currently it is captured in the version URI

**Comment by jhaag75** [comment]
where would this field be added?

**Comment by fugu13** [comment]
In the top level, with the other general metadata

**Comment by fugu13** [comment]
I'm increasingly thinking it may be more appropriate to not include this field and not use semantic versioning.

Semantic versioning is designed around software. A standard for describing documents doesn't really fit the model. Having each document describe adhering to different patch versions despite there being no document-affecting differences is... not just weird, but counterproductive -- it means version numbers need to be constantly parsed for no gain whatsoever.

Instead, I propose we only use version URIs, and that version numbers be major+minor version, optionally with a development suffix. If the structure of the document is "mostly the same", minor version is incremented, and if it is "very very different" major version is incremented.
